### ISSUE TITLE
Stories not open In IOS

### ISSUE THREAD

**Issue by yogesh048** [birdwingo/react-native-instagram-stories#8]
Dear Team,

I hope this message finds you well.

We have successfully integrated your package into our project. It is functioning seamlessly on Android; however, we are encountering an issue on iOS. Specifically, when we attempt to click on a user image, the stories do not open.

Could you kindly provide guidance on how to address this matter? Any assistance you can offer would be greatly appreciated.

**Comment by Lipo11** [comment]
Hello! thanks for using our library :) are you using stories inside of modal? Because on iOS there is allowed only one modal opened ( stories is using modal ). if so, please create your custom view with absolute position and width, height 100%.
If this is not a problem, please try to debug touchableOpacity onPress inside avatar component.
let us know if problem is solved, thanks!
